language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
      - r-packages-trusty
      - sourceline: "ppa:marutter/rrutter"
      - sourceline: "ppa:marutter/c2d4u"
    packages:
      - google-chrome-beta
      - r-recommended
      - r-cran-jsonlite
      - r-cran-r6
env:
  - CHROME_PATH=/usr/bin/google-chrome-beta R_LIBS_USER=~/R/Library
install:
  - yarn install
  - mkdir -p ~/R/Library
  - Rscript --version
after_script:
  - yarn lerna run report
