sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
      - r-recommended
env:
  - CHROME_BIN=/usr/bin/google-chrome-beta R_LIBS=~/Rlibs
install:
  - npm install
  - bower install
  - mkdir ~/Rlibs
  - Rscript --version
  - Rscript -e "install.packages(c('tidyverse', 'tidyjson'), repos='https://cran.cnr.berkeley.edu/')"
before_script:
  - Rscript -e "wilcox.test(mpg ~ am, data=mtcars)"
