language: node_js
node_js:
  - 'stable'
cache: yarn
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - CHROME_PATH=/usr/bin/google-chrome-stable
install:
  - yarn install
script:
  - yarn test
  - yarn lint
after_script:
  - yarn lerna run report
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
