language: node_js
node_js:
  - 'stable'
cache: yarn
sudo: required
dist: xenial
addons:
  chrome: stable
env:
  - CHROME_PATH=/usr/bin/google-chrome-stable
install:
  - yarn install
script:
  - yarn test
  - yarn lint
after_script:
  - yarn lerna run report
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
